# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpaceX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpaceX
pod 'Alamofire', '~> 5.0.0-rc.3'

  target 'SpaceXTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Nimble', '~> 8.0'
pod 'Quick', '~> 2.2'
  end

  target 'SpaceXUITests' do
    # Pods for testing
  end

end
